// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Infrastructure.Data;

#nullable disable

namespace Test.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20260122085549_SeededUsers")]
    partial class SeededUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Follower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("FollowingId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01",
                            Avatar = "/avatars/u1.png",
                            Bio = "Backend developer • ASP.NET • Linux",
                            CreatedAt = new DateTime(2024, 12, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            Email = "bozhidar@example.com",
                            UserName = "bozhidar"
                        },
                        new
                        {
                            Id = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902",
                            Avatar = "/avatars/u2.png",
                            Bio = "Frontend dev • React",
                            CreatedAt = new DateTime(2024, 12, 3, 11, 20, 0, 0, DateTimeKind.Utc),
                            Email = "alex@example.com",
                            UserName = "alex"
                        },
                        new
                        {
                            Id = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903",
                            Avatar = "/avatars/u3.png",
                            Bio = "UI / UX designer",
                            CreatedAt = new DateTime(2024, 12, 5, 15, 45, 0, 0, DateTimeKind.Utc),
                            Email = "maria@example.com",
                            UserName = "maria"
                        },
                        new
                        {
                            Id = "c91e9189-281f-48c3-b8ad-1b20f4f10104",
                            Avatar = "/avatars/u4.png",
                            Bio = "Cybersecurity student",
                            CreatedAt = new DateTime(2024, 12, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nikola@example.com",
                            UserName = "nikola"
                        },
                        new
                        {
                            Id = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105",
                            Avatar = "/avatars/u5.png",
                            Bio = "Digital artist",
                            CreatedAt = new DateTime(2024, 12, 7, 12, 40, 0, 0, DateTimeKind.Utc),
                            Email = "elena@example.com",
                            UserName = "elena"
                        },
                        new
                        {
                            Id = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106",
                            Avatar = "/avatars/u6.png",
                            Bio = "DevOps • Docker • Kubernetes",
                            CreatedAt = new DateTime(2024, 12, 9, 8, 10, 0, 0, DateTimeKind.Utc),
                            Email = "ivan@example.com",
                            UserName = "ivan"
                        },
                        new
                        {
                            Id = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107",
                            Avatar = "/avatars/u7.png",
                            Bio = "Game developer",
                            CreatedAt = new DateTime(2024, 12, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Email = "petar@example.com",
                            UserName = "petar"
                        },
                        new
                        {
                            Id = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108",
                            Avatar = "/avatars/u8.png",
                            Bio = "Computer science student",
                            CreatedAt = new DateTime(2024, 12, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sofia@example.com",
                            UserName = "sofia"
                        },
                        new
                        {
                            Id = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109",
                            Avatar = "/avatars/u9.png",
                            Bio = "Tech blogger",
                            CreatedAt = new DateTime(2024, 12, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "george@example.com",
                            UserName = "george"
                        },
                        new
                        {
                            Id = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110",
                            Avatar = "/avatars/u10.png",
                            Bio = "Marketing specialist",
                            CreatedAt = new DateTime(2024, 12, 14, 9, 20, 0, 0, DateTimeKind.Utc),
                            Email = "victoria@example.com",
                            UserName = "victoria"
                        },
                        new
                        {
                            Id = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111",
                            Avatar = "/avatars/u11.png",
                            Bio = "Mobile developer",
                            CreatedAt = new DateTime(2024, 12, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daniel@example.com",
                            UserName = "daniel"
                        },
                        new
                        {
                            Id = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112",
                            Avatar = "/avatars/u12.png",
                            Bio = "QA engineer",
                            CreatedAt = new DateTime(2024, 12, 16, 11, 10, 0, 0, DateTimeKind.Utc),
                            Email = "teodora@example.com",
                            UserName = "teodora"
                        },
                        new
                        {
                            Id = "4b46a84d-21a3-44db-9d2f-68c2f51f3113",
                            Avatar = "/avatars/u13.png",
                            Bio = "Java developer",
                            CreatedAt = new DateTime(2024, 12, 17, 10, 10, 0, 0, DateTimeKind.Utc),
                            Email = "martin@example.com",
                            UserName = "martin"
                        },
                        new
                        {
                            Id = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114",
                            Avatar = "/avatars/u14.png",
                            Bio = "Blockchain enthusiast",
                            CreatedAt = new DateTime(2024, 12, 18, 19, 30, 0, 0, DateTimeKind.Utc),
                            Email = "kaloyan@example.com",
                            UserName = "kaloyan"
                        },
                        new
                        {
                            Id = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115",
                            Avatar = "/avatars/u15.png",
                            Bio = "Product manager",
                            CreatedAt = new DateTime(2024, 12, 19, 8, 50, 0, 0, DateTimeKind.Utc),
                            Email = "irina@example.com",
                            UserName = "irina"
                        },
                        new
                        {
                            Id = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116",
                            Avatar = "/avatars/u16.png",
                            Bio = "Cloud engineer",
                            CreatedAt = new DateTime(2024, 12, 20, 12, 10, 0, 0, DateTimeKind.Utc),
                            Email = "stefan@example.com",
                            UserName = "stefan"
                        },
                        new
                        {
                            Id = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117",
                            Avatar = "/avatars/u17.png",
                            Bio = "HR & recruiting",
                            CreatedAt = new DateTime(2024, 12, 21, 14, 15, 0, 0, DateTimeKind.Utc),
                            Email = "nadya@example.com",
                            UserName = "nadya"
                        },
                        new
                        {
                            Id = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118",
                            Avatar = "/avatars/u18.png",
                            Bio = "Startup founder",
                            CreatedAt = new DateTime(2024, 12, 22, 17, 40, 0, 0, DateTimeKind.Utc),
                            Email = "rado@example.com",
                            UserName = "rado"
                        });
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Follower", b =>
                {
                    b.HasOne("Test.Infrastructure.Data.Model.User", "FollowerUser")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Test.Infrastructure.Data.Model.User", "FollowingUser")
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FollowerUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Message", b =>
                {
                    b.HasOne("Test.Infrastructure.Data.Model.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Test.Infrastructure.Data.Model.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Test.Infrastructure.Data.Model.Post", b =>
                {
                    b.HasOne("Test.Infrastructure.Data.Model.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
